version: '3.7'

services:
  proxy:
    image: 'nginx:1.23.2-alpine'
    container_name: 'js-libs-bot-dev-proxy'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8081:80
    command: [nginx, '-g', 'daemon off;']